version: 0.0
os: linux
files:
  # - source: scripts/stop_pm2.sh
  #   destination: /opt/codedeploy-agent/deployment-root/${DEPLOYMENT_ID}/deployment-archive/scripts/stop_pm2.sh
  # - source: scripts/before_install.sh
  #   destination: /opt/codedeploy-agent/deployment-root/${DEPLOYMENT_ID}/deployment-archive/scripts/before_install.sh
  # - source: scripts/install_dependencies.sh
  #   destination: /opt/codedeploy-agent/deployment-root/${DEPLOYMENT_ID}/deployment-archive/scripts/install_dependencies.sh
  # - source: scripts/start_server.sh
  #   destination: /opt/codedeploy-agent/deployment-root/${DEPLOYMENT_ID}/deployment-archive/scripts/start_server.sh
  # - source: scripts/validate_service.sh
  #   destination: /opt/codedeploy-agent/deployment-root/${DEPLOYMENT_ID}/deployment-archive/scripts/validate_service.sh
  - source: /
    destination: /home/ec2-user/app
  
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root 
  Install:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ec2-user