name: CD pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  upload-S3:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Zip files before upload (with exclusions)
      run: zip -r app_files.zip . -x "node_modules/*" "cypress/*" "spec/*" ".git/*" ".github/*" "cypress.config.js" "jest.config.js"

    - name: Upload zip file to S3
      run: aws s3 cp app_files.zip s3://mantasdean-acebook/app_files.zip
