name: CI pipeline

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]
        mongodb-version: ['8.0']

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependecies
      run: npm install
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        
    - name: Start server in background
      run: |
        npm run start:test &
        sleep 5

    - name: Run tests
      run: npm run test 