name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]
        mongodb-version: ['8.0']

    # services:
    #   mongodb:
    #     image: mongo:8.0
    #     ports:
    #       - 27017:27017

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install dependecies
      run: npm install

    # - name: Install MongoDB
    #   run: |
    #     sudo apt-get install gnupg curl
    #     curl -fsSL https://www.mongodb.org/static/pgp/server-8.0.asc | sudo gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg --dearmor
    #     echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/8.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-8.0.list
    #     sudo apt-get update
    #     sudo apt-get install -y mongodb-org
    #     sudo systemctl start mongod
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        
    - name: Start server in background
      run: |
        npm run start:test &
        sleep 5

    - name: Run tests
      run: npm run test 

